# Generated by Django 3.1 on 2020-08-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='TSAWebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsa_title', models.CharField(max_length=200)),
                ('tsa_content', models.TextField(verbose_name='Hello World')),
            ],
        ),
    ]
